### ISSUE TITLE
Search LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by cedrusx** [zdzhaoyong/Svar#3]
Currently svar.load searches under `PATH`, so users need to install their libraries into the system. This is inconvenient sometimes, e.g. when one just wants to export a module within the same catkin workspace. So suggesting to search `LD_LIBRARY_PATH` as well.

**Comment by zdzhaoyong** [comment]
Yes, thanks for the advice! 
**LD_LIBRARY_PATH** is already supported, please try it out~

**Comment by cedrusx** [comment]
> Yes, thanks for the advice!
> `LD_LIBRARY_PATH` is already supported, please try it out~

Have you checked in? I did not see any new commits.

**Comment by zdzhaoyong** [comment]
> > Yes, thanks for the advice!
> > `LD_LIBRARY_PATH` is already supported, please try it out~
> 
> Have you checked in? I did not see any new commits.

It already existed before.

**Comment by cedrusx** [comment]
It does not work. I just created a [pull request](https://github.com/zdzhaoyong/Svar/pull/5) to fix the issue. Would you take a look?

**Comment by zdzhaoyong** [comment]
> It does not work. I just created a [pull request](https://github.com/zdzhaoyong/Svar/pull/5) to fix the issue. Would you take a look?

It is merged, thanks for your contribution!
